name: Example TestWorkflow


on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: action/checkout@v2
    - name: Use Github API with PAT
      env:
        GITHUB_TOKEN: ${{secrets.GH_PAT}}
      run: |
       curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user
      
  
